### ISSUE TITLE
Incorrect types for NftMetadata.image

### ISSUE THREAD

**Issue by alex-lighthouse** [alchemyplatform/alchemy-web3#134]
Network: Ethereum
API request: getNFTs

Easiest way to replicate: /getNFTs on wallet address 0x2bdeA27111B606551a1D3c19c0e8c73e0081ecBA

One NFT has metadata.image and the other has metadata.image_url

I get that this is not exactly an issue with the typing but more at the API level. Feel free to redirect this issue anywhere that would be best to address it.

Thanks!

**Comment by thebrianchen** [comment]
@alex-lighthouse Thanks for filing an issue! The fields under `metadata` are the raw metadata that Alchemy has scraped from the original metadata url in the NFT, so we have no control over the names of the fields.

The `media` and `tokenUri` field contain Alchemy's best effort at parsing the metadata. Most NFTs list the image url field as `image`, rather than `image_url`, so the particular NFT you've listed in the example didn't get ingested. I'll check with the backend engineers to see if it makes sense to also ingest `image_url` fields, but that depends on the number of NFTs that use that standard.

I'm going to mark that issue as closed since this is WAI, but feel free to ask any other questions you may have.
